knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(GOOGLE_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_CLIENT_SECRET)%'
            # C'est le nom de la route Symfony vers laquelle Google va nous renvoyer
            redirect_route: connect_google_check
            redirect_params: { }
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
