--
-- PostgreSQL database dump
--

\restrict wg3umkTeDebgVaNcqERaF7tNcGYwoukFpPTxs21DDlUZgu37jl4ggdZxDRWbhOl

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat_message (
    id integer NOT NULL,
    user_id uuid NOT NULL,
    role character varying(10) NOT NULL,
    content text NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.chat_message OWNER TO postgres;

--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.chat_message_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.chat_message_id_seq OWNER TO postgres;

--
-- Name: chat_message_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.chat_message_id_seq OWNED BY public.chat_message.id;


--
-- Name: chat_message_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_activity_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.daily_activity_log (
    id uuid NOT NULL,
    logged_on date NOT NULL,
    step_count integer NOT NULL,
    active_calories smallint,
    sleep_minutes smallint,
    notes text,
    created_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.daily_activity_log OWNER TO postgres;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO postgres;

--
-- Name: exercise; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise (
    id uuid NOT NULL,
    name character varying(150) NOT NULL,
    muscle_group character varying(30) NOT NULL,
    equipment character varying(50) DEFAULT NULL::character varying,
    description text,
    created_by_id uuid
);


ALTER TABLE public.exercise OWNER TO postgres;

--
-- Name: exercise_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.exercise_template (
    id uuid NOT NULL,
    "position" smallint NOT NULL,
    target_sets smallint NOT NULL,
    target_reps_min smallint NOT NULL,
    target_reps_max smallint NOT NULL,
    target_weight_kg numeric(6,2) DEFAULT NULL::numeric,
    rest_seconds smallint,
    notes text,
    workout_template_id uuid NOT NULL,
    exercise_id uuid NOT NULL
);


ALTER TABLE public.exercise_template OWNER TO postgres;

--
-- Name: messenger_messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messenger_messages (
    id bigint NOT NULL,
    body text NOT NULL,
    headers text NOT NULL,
    queue_name character varying(190) NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    available_at timestamp(0) without time zone NOT NULL,
    delivered_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);


ALTER TABLE public.messenger_messages OWNER TO postgres;

--
-- Name: messenger_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messenger_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messenger_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: nutrition_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nutrition_log (
    id uuid NOT NULL,
    logged_on date NOT NULL,
    proteins_g smallint NOT NULL,
    carbs_g smallint NOT NULL,
    fats_g smallint NOT NULL,
    kcal smallint NOT NULL,
    fiber_g smallint,
    water_l numeric(4,2) DEFAULT NULL::numeric,
    notes text,
    created_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL,
    image_filename character varying(255) DEFAULT NULL::character varying,
    water_ml integer
);


ALTER TABLE public.nutrition_log OWNER TO postgres;

--
-- Name: program; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.program (
    id uuid NOT NULL,
    name character varying(150) NOT NULL,
    description text,
    duration_weeks smallint,
    created_at timestamp(0) without time zone NOT NULL,
    created_by_id uuid NOT NULL
);


ALTER TABLE public.program OWNER TO postgres;

--
-- Name: program_assignment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.program_assignment (
    id uuid NOT NULL,
    start_date date NOT NULL,
    end_date date,
    is_active boolean NOT NULL,
    program_id uuid NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE public.program_assignment OWNER TO postgres;

--
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id uuid NOT NULL,
    email character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    height_cm smallint,
    sex character varying(10) DEFAULT NULL::character varying,
    birth_date date,
    created_at timestamp(0) without time zone NOT NULL,
    coach_id uuid,
    google_access_token text,
    google_refresh_token text,
    google_access_expires_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    current_streak integer DEFAULT 0 NOT NULL,
    longest_streak integer DEFAULT 0 NOT NULL,
    last_active_date date
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- Name: weight_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.weight_log (
    id uuid NOT NULL,
    weight_kg numeric(5,2) NOT NULL,
    logged_on date NOT NULL,
    notes text,
    created_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL,
    fat_percent numeric(4,1) DEFAULT NULL::numeric,
    fat_kg numeric(5,2) DEFAULT NULL::numeric,
    muscle_kg numeric(5,2) DEFAULT NULL::numeric,
    bone_kg numeric(4,2) DEFAULT NULL::numeric,
    water_percent numeric(4,1) DEFAULT NULL::numeric,
    bmi numeric(4,1) DEFAULT NULL::numeric,
    bmr smallint,
    source character varying(20) DEFAULT NULL::character varying,
    image_filename character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public.weight_log OWNER TO postgres;

--
-- Name: workout_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_session (
    id uuid NOT NULL,
    name character varying(150) NOT NULL,
    performed_at timestamp(0) without time zone NOT NULL,
    duration_minutes smallint,
    rpe smallint,
    notes text,
    created_at timestamp(0) without time zone NOT NULL,
    user_id uuid NOT NULL,
    source_template_id uuid
);


ALTER TABLE public.workout_session OWNER TO postgres;

--
-- Name: workout_set; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_set (
    id uuid NOT NULL,
    exercise_position smallint NOT NULL,
    set_number smallint NOT NULL,
    reps smallint NOT NULL,
    weight_kg numeric(6,2) DEFAULT NULL::numeric,
    rpe smallint,
    distance_m integer,
    duration_seconds integer,
    is_warmup boolean NOT NULL,
    session_id uuid NOT NULL,
    exercise_id uuid NOT NULL
);


ALTER TABLE public.workout_set OWNER TO postgres;

--
-- Name: workout_template; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workout_template (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    day_of_week smallint,
    program_id uuid NOT NULL
);


ALTER TABLE public.workout_template OWNER TO postgres;

--
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.chat_message (id, user_id, role, content, created_at) FROM stdin;
1	019df91c-4502-7de3-8e3a-229bb15d9f5f	user	combien kilo je dois perdre ?	2026-05-22 18:14:08
2	019df91c-4502-7de3-8e3a-229bb15d9f5f	model	Une erreur est survenue lors de la communication avec l'IA. Réessaie dans un moment.	2026-05-22 18:14:08
\.


--
-- Data for Name: daily_activity_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.daily_activity_log (id, logged_on, step_count, active_calories, sleep_minutes, notes, created_at, user_id) FROM stdin;
\.


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260505163521	2026-05-05 16:35:31	106
DoctrineMigrations\\Version20260505175057	2026-05-05 17:51:21	27
DoctrineMigrations\\Version20260508090050	2026-05-08 09:00:59	71
DoctrineMigrations\\Version20260508141952	2026-05-08 14:20:06	34
DoctrineMigrations\\Version20260509120000	2026-05-11 12:01:21	41
DoctrineMigrations\\Version20260518120000	2026-05-22 17:57:06	99
DoctrineMigrations\\Version20260522175753	2026-05-22 17:58:45	11
DoctrineMigrations\\Version20260522183225	2026-05-22 18:32:45	8
DoctrineMigrations\\Version20260522183847	2026-05-22 18:39:29	6
\.


--
-- Data for Name: exercise; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercise (id, name, muscle_group, equipment, description, created_by_id) FROM stdin;
019df91c-44da-7bd0-bf3e-8f74f3b404f5	Développé couché barre	chest	barbell	\N	\N
019df91c-44db-72d3-9296-68025f0375d1	Développé incliné haltères	chest	dumbbell	\N	\N
019df91c-44db-75b3-9296-68025f421d96	Élévations latérales	shoulders	dumbbell	\N	\N
019df91c-44db-7823-9296-68025fa6ae42	Développé militaire haltères	shoulders	dumbbell	\N	\N
019df91c-44db-7b83-9296-68025fe6c17a	Dips / Pushdown poulie triceps	triceps	bodyweight	\N	\N
019df91c-44db-7d57-9296-6802606dbb6f	Soulevé de terre roumain	back	barbell	\N	\N
019df91c-44db-7f1f-9296-68026142fb35	Tirage vertical (tractions assistées)	back	cable	\N	\N
019df91c-44dc-714e-ad07-4555ce2ee90c	Rowing barre ou haltères	back	barbell	\N	\N
019df91c-44dc-733a-ad07-4555ce79a5c8	Tirage horizontal poulie	back	cable	\N	\N
019df91c-44dc-7526-ad07-4555ce9fc319	Curl barre EZ	biceps	barbell	\N	\N
019df91c-44dc-76fe-ad07-4555cec0a3b0	Squat barre (ou Hack Squat)	quads	barbell	\N	\N
019df91c-44dc-78be-ad07-4555cf3999f6	Presse à cuisses	quads	machine	\N	\N
019df91c-44dc-7a82-ad07-4555d00cff72	Fentes marchées haltères	quads	dumbbell	\N	\N
019df91c-44dc-7ca2-ad07-4555d01477de	Leg curl allongé	hamstrings	machine	\N	\N
019df91c-44dc-7eca-ad07-4555d081fcb5	Hip Thrust / Ponte fessiers	glutes	barbell	\N	\N
019df91c-44dd-710c-868e-14c162cba9db	Mollets debout	calves	machine	\N	\N
019df91c-44dd-72d8-868e-14c162e4df3f	Cardio LISS — Vélo / Tapis (fin séance)	cardio	machine	\N	\N
019df91c-44dd-74ac-868e-14c163e3db55	Cardio longue durée (vélo, natation, elliptique)	cardio	machine	\N	\N
\.


--
-- Data for Name: exercise_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.exercise_template (id, "position", target_sets, target_reps_min, target_reps_max, target_weight_kg, rest_seconds, notes, workout_template_id, exercise_id) FROM stdin;
019df91c-46d0-79e4-a8e2-4ecb5fa6f886	0	4	6	8	\N	180	Exercice principal. Priorité à la charge progressive.	019df91c-46d0-7834-a8e2-4ecb5f64cf8b	019df91c-44da-7bd0-bf3e-8f74f3b404f5
019df91c-46d0-7b08-a8e2-4ecb5fdbdf4c	1	3	10	10	\N	120	\N	019df91c-46d0-7834-a8e2-4ecb5f64cf8b	019df91c-44db-72d3-9296-68025f0375d1
019df91c-46d0-7c54-a8e2-4ecb609a171b	2	4	12	12	\N	90	Prendre léger, contrôle total de la montée.	019df91c-46d0-7834-a8e2-4ecb5f64cf8b	019df91c-44db-75b3-9296-68025f421d96
019df91c-46d0-7d58-a8e2-4ecb61661c84	3	3	10	10	\N	120	\N	019df91c-46d0-7834-a8e2-4ecb5f64cf8b	019df91c-44db-7823-9296-68025fa6ae42
019df91c-46d0-7e4c-a8e2-4ecb6249b9a7	4	3	12	12	\N	90	Dips lestés ou pushdown poulie selon niveau.	019df91c-46d0-7834-a8e2-4ecb5f64cf8b	019df91c-44db-7b83-9296-68025fe6c17a
019df91c-46d0-7f40-a8e2-4ecb6256abe8	5	1	20	20	\N	\N	LISS fin de séance — 60 à 70% FC max.	019df91c-46d0-7834-a8e2-4ecb5f64cf8b	019df91c-44dd-72d8-868e-14c162e4df3f
019df91c-46d1-7150-8ee1-0be699285a04	0	4	6	8	\N	180	Attention au bas du dos. Garder le buste neutre.	019df91c-46d1-703c-8ee1-0be69898ff44	019df91c-44db-7d57-9296-6802606dbb6f
019df91c-46d1-7260-8ee1-0be699be1a37	1	4	8	10	\N	120	Tractions assistées si possible — viser la ROM complète.	019df91c-46d1-703c-8ee1-0be69898ff44	019df91c-44db-7f1f-9296-68026142fb35
019df91c-46d1-7350-8ee1-0be69a16661e	2	3	10	10	\N	120	\N	019df91c-46d1-703c-8ee1-0be69898ff44	019df91c-44dc-714e-ad07-4555ce2ee90c
019df91c-46d1-7494-8ee1-0be69a3e61f7	3	3	12	12	\N	90	\N	019df91c-46d1-703c-8ee1-0be69898ff44	019df91c-44dc-733a-ad07-4555ce79a5c8
019df91c-46d1-7594-8ee1-0be69a5b5754	4	3	12	12	\N	90	Supination complète en haut.	019df91c-46d1-703c-8ee1-0be69898ff44	019df91c-44dc-7526-ad07-4555ce9fc319
019df91c-46d1-7658-8ee1-0be69ac63256	5	1	20	20	\N	\N	LISS fin de séance — 60 à 70% FC max.	019df91c-46d1-703c-8ee1-0be69898ff44	019df91c-44dd-72d8-868e-14c162e4df3f
019df91c-46d1-77f8-8ee1-0be69bc41866	0	4	6	8	\N	180	Squat barre haute ou Hack Squat machine.	019df91c-46d1-76f4-8ee1-0be69bbcc172	019df91c-44dc-76fe-ad07-4555cec0a3b0
019df91c-46d1-78f4-8ee1-0be69c681d5e	1	3	10	10	\N	120	\N	019df91c-46d1-76f4-8ee1-0be69bbcc172	019df91c-44dc-78be-ad07-4555cf3999f6
019df91c-46d1-79e8-8ee1-0be69c716e07	2	3	12	12	\N	120	12 reps par côté. Fentes marchées ou alternées.	019df91c-46d1-76f4-8ee1-0be69bbcc172	019df91c-44dc-7a82-ad07-4555d00cff72
019df91c-46d1-7ad8-8ee1-0be69c90f13d	3	3	12	12	\N	90	\N	019df91c-46d1-76f4-8ee1-0be69bbcc172	019df91c-44dc-7ca2-ad07-4555d01477de
019df91c-46d1-7be0-8ee1-0be69c97e664	4	3	15	15	\N	120	Hip thrust barre ou ponte fessiers. Squeeze en haut.	019df91c-46d1-76f4-8ee1-0be69bbcc172	019df91c-44dc-7eca-ad07-4555d081fcb5
019df91c-46d1-7d60-8ee1-0be69cc69395	5	4	15	15	\N	60	Tempo lent 2-0-2. ROM complète.	019df91c-46d1-76f4-8ee1-0be69bbcc172	019df91c-44dd-710c-868e-14c162cba9db
019df91c-46d1-7e28-8ee1-0be69cff48d0	6	1	20	20	\N	\N	LISS fin de séance — 60 à 70% FC max.	019df91c-46d1-76f4-8ee1-0be69bbcc172	019df91c-44dd-72d8-868e-14c162e4df3f
019df91c-46d2-7026-ac92-7368c35619de	0	1	45	60	\N	\N	Vélo, natation, elliptique ou marche rapide. Zone cible: 60-70% FC max (~115-135 bpm).	019df91c-46d1-7ec0-8ee1-0be69dc5846a	019df91c-44dd-74ac-868e-14c163e3db55
\.


--
-- Data for Name: messenger_messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messenger_messages (id, body, headers, queue_name, created_at, available_at, delivered_at) FROM stdin;
\.


--
-- Data for Name: nutrition_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.nutrition_log (id, logged_on, proteins_g, carbs_g, fats_g, kcal, fiber_g, water_l, notes, created_at, user_id, image_filename, water_ml) FROM stdin;
\.


--
-- Data for Name: program; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.program (id, name, description, duration_weeks, created_at, created_by_id) FROM stdin;
019df91c-46d0-762c-a8e2-4ecb5e9d8a24	PPL + Cardio — 121 → 95 kg	Programme 4 jours/semaine. Objectif: perdre ~26 kg de graisse en préservant la masse musculaire. Déficit calorique de ~500 kcal/jour sur maintenance (~3 200 kcal). 2 700 kcal · 190g Prot · 270g Gluc · 75g Lip.	36	2026-05-05 17:07:53	019df91c-4502-7de3-8e3a-229bb15d9f5f
\.


--
-- Data for Name: program_assignment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.program_assignment (id, start_date, end_date, is_active, program_id, user_id) FROM stdin;
019df91c-46d2-70ca-ac92-7368c40986a6	2026-05-05	\N	t	019df91c-46d0-762c-a8e2-4ecb5e9d8a24	019df91c-4502-7de3-8e3a-229bb15d9f5f
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."user" (id, email, roles, password, first_name, last_name, height_cm, sex, birth_date, created_at, coach_id, google_access_token, google_refresh_token, google_access_expires_at, current_streak, longest_streak, last_active_date) FROM stdin;
019df91c-4502-7de3-8e3a-229bb15d9f5f	leonard.donavan@gmail.com	["ROLE_COACH"]	$2y$13$jZPZPE8.oFXEf9faLKpIYeA8UvUDuypu.B31bl4T6QwuArR7Ps7U6	Donavan	Leonard	183	male	1995-01-01	2026-05-05 17:07:52	\N	\N	\N	\N	0	0	\N
\.


--
-- Data for Name: weight_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.weight_log (id, weight_kg, logged_on, notes, created_at, user_id, fat_percent, fat_kg, muscle_kg, bone_kg, water_percent, bmi, bmr, source, image_filename) FROM stdin;
019e30e5-5640-7e5e-9af4-377202187127	120.10	2026-05-16	Graisse viscérale: 13	2026-05-16 13:06:36	019df91c-4502-7de3-8e3a-229bb15d9f5f	30.8	37.00	79.00	4.10	49.0	35.9	2547	boditrax_csv	\N
019df94b-f8cb-7f2f-8740-97b7a2daba31	121.20	2026-05-03	Graisse viscérale: 14	2026-05-05 17:59:58	019df91c-4502-7de3-8e3a-229bb15d9f5f	31.0	37.60	79.50	4.10	48.9	36.6	2565	boditrax_csv	\N
019df94b-f8cd-7104-8e69-51a5335fd0d2	118.70	2026-02-22	Graisse viscérale: 13	2026-05-05 17:59:58	019df91c-4502-7de3-8e3a-229bb15d9f5f	30.8	36.60	78.10	4.00	49.2	35.8	2513	boditrax_csv	\N
019df94b-f8cd-7ee0-8e69-51a5338b975b	118.30	2026-01-25	Graisse viscérale: 13	2026-05-05 17:59:58	019df91c-4502-7de3-8e3a-229bb15d9f5f	30.2	35.70	78.60	4.00	49.5	35.7	2529	boditrax_csv	\N
019df94b-f8ce-7db0-85fc-385d3a49a83a	113.50	2025-09-20	Graisse viscérale: 12	2026-05-05 17:59:58	019df91c-4502-7de3-8e3a-229bb15d9f5f	30.2	34.30	75.30	3.90	49.9	35.0	2416	boditrax_csv	\N
019df94b-f8cf-7d3f-9779-c5a25e85b918	116.30	2025-08-17	Graisse viscérale: 13	2026-05-05 17:59:58	019df91c-4502-7de3-8e3a-229bb15d9f5f	30.6	35.60	76.70	4.00	49.6	35.9	2468	boditrax_csv	\N
019df94b-f8d0-7964-86ee-74b122cc50d9	115.60	2025-07-06	Graisse viscérale: 17	2026-05-05 17:59:58	019df91c-4502-7de3-8e3a-229bb15d9f5f	35.2	40.70	71.20	3.70	48.4	40.0	2306	boditrax_csv	\N
019df94b-f8d1-7781-9f96-3b7995b606ef	115.10	2025-06-13	Graisse viscérale: 16	2026-05-05 17:59:58	019df91c-4502-7de3-8e3a-229bb15d9f5f	34.4	39.60	71.80	3.70	49.0	39.8	2321	boditrax_csv	\N
019df94b-f8d2-766f-8391-38960de23893	116.30	2025-05-14	Graisse viscérale: 17	2026-05-05 17:59:58	019df91c-4502-7de3-8e3a-229bb15d9f5f	34.5	40.10	72.50	3.70	48.9	40.2	2344	boditrax_csv	\N
\.


--
-- Data for Name: workout_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_session (id, name, performed_at, duration_minutes, rpe, notes, created_at, user_id, source_template_id) FROM stdin;
019e3211-a8bc-705d-a6cc-bc5845f189e5	cardio	2026-05-16 08:34:00	42	\N		2026-05-16 18:34:38	019df91c-4502-7de3-8e3a-229bb15d9f5f	019df91c-46d1-7ec0-8ee1-0be69dc5846a
\.


--
-- Data for Name: workout_set; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_set (id, exercise_position, set_number, reps, weight_kg, rpe, distance_m, duration_seconds, is_warmup, session_id, exercise_id) FROM stdin;
\.


--
-- Data for Name: workout_template; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workout_template (id, name, day_of_week, program_id) FROM stdin;
019df91c-46d0-7834-a8e2-4ecb5f64cf8b	PUSH — Poitrine / Épaules / Triceps	1	019df91c-46d0-762c-a8e2-4ecb5e9d8a24
019df91c-46d1-703c-8ee1-0be69898ff44	PULL — Dos / Biceps	3	019df91c-46d0-762c-a8e2-4ecb5e9d8a24
019df91c-46d1-76f4-8ee1-0be69bbcc172	LEGS — Cuisses / Fessiers / Mollets	5	019df91c-46d0-762c-a8e2-4ecb5e9d8a24
019df91c-46d1-7ec0-8ee1-0be69dc5846a	CARDIO DÉDIÉ — Longue durée	6	019df91c-46d0-762c-a8e2-4ecb5e9d8a24
\.


--
-- Name: chat_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_message_id_seq', 2, true);


--
-- Name: chat_message_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.chat_message_id_seq1', 1, false);


--
-- Name: messenger_messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messenger_messages_id_seq', 1, false);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: daily_activity_log daily_activity_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_activity_log
    ADD CONSTRAINT daily_activity_log_pkey PRIMARY KEY (id);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: exercise exercise_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise
    ADD CONSTRAINT exercise_pkey PRIMARY KEY (id);


--
-- Name: exercise_template exercise_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_template
    ADD CONSTRAINT exercise_template_pkey PRIMARY KEY (id);


--
-- Name: messenger_messages messenger_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messenger_messages
    ADD CONSTRAINT messenger_messages_pkey PRIMARY KEY (id);


--
-- Name: nutrition_log nutrition_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nutrition_log
    ADD CONSTRAINT nutrition_log_pkey PRIMARY KEY (id);


--
-- Name: program_assignment program_assignment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.program_assignment
    ADD CONSTRAINT program_assignment_pkey PRIMARY KEY (id);


--
-- Name: program program_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT program_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: weight_log weight_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.weight_log
    ADD CONSTRAINT weight_log_pkey PRIMARY KEY (id);


--
-- Name: workout_session workout_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_session
    ADD CONSTRAINT workout_session_pkey PRIMARY KEY (id);


--
-- Name: workout_set workout_set_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_set
    ADD CONSTRAINT workout_set_pkey PRIMARY KEY (id);


--
-- Name: workout_template workout_template_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_template
    ADD CONSTRAINT workout_template_pkey PRIMARY KEY (id);


--
-- Name: idx_18b697fa76ed395; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_18b697fa76ed395 ON public.nutrition_log USING btree (user_id);


--
-- Name: idx_26ffb90e3eb8070a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_26ffb90e3eb8070a ON public.program_assignment USING btree (program_id);


--
-- Name: idx_26ffb90ea76ed395; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_26ffb90ea76ed395 ON public.program_assignment USING btree (user_id);


--
-- Name: idx_4f11f2353eb8070a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_4f11f2353eb8070a ON public.workout_template USING btree (program_id);


--
-- Name: idx_6bbb9e9ca76ed395; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_6bbb9e9ca76ed395 ON public.weight_log USING btree (user_id);


--
-- Name: idx_6fdefb94613fecdf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_6fdefb94613fecdf ON public.workout_set USING btree (session_id);


--
-- Name: idx_6fdefb94e934951a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_6fdefb94e934951a ON public.workout_set USING btree (exercise_id);


--
-- Name: idx_70dabd61a76ed395; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_70dabd61a76ed395 ON public.daily_activity_log USING btree (user_id);


--
-- Name: idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_75ea56e0fb7336f0e3bd61ce16ba31dbbf396750 ON public.messenger_messages USING btree (queue_name, available_at, delivered_at, id);


--
-- Name: idx_910cbf6b8db41c9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_910cbf6b8db41c9 ON public.exercise_template USING btree (workout_template_id);


--
-- Name: idx_910cbf6be934951a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_910cbf6be934951a ON public.exercise_template USING btree (exercise_id);


--
-- Name: idx_92ed7784b03a8386; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_92ed7784b03a8386 ON public.program USING btree (created_by_id);


--
-- Name: idx_ac82b97c39a55f18; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ac82b97c39a55f18 ON public.workout_session USING btree (source_template_id);


--
-- Name: idx_ac82b97ca76ed395; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_ac82b97ca76ed395 ON public.workout_session USING btree (user_id);


--
-- Name: idx_aedad51cb03a8386; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_aedad51cb03a8386 ON public.exercise USING btree (created_by_id);


--
-- Name: idx_assignment_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_assignment_active ON public.program_assignment USING btree (user_id, is_active);


--
-- Name: idx_chat_user_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_chat_user_date ON public.chat_message USING btree (user_id, created_at);


--
-- Name: idx_exercise_muscle; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_exercise_muscle ON public.exercise USING btree (muscle_group);


--
-- Name: idx_session_user_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_session_user_date ON public.workout_session USING btree (user_id, performed_at);


--
-- Name: idx_user_coach; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_coach ON public."user" USING btree (coach_id);


--
-- Name: uniq_8d93d649e7927c74; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_8d93d649e7927c74 ON public."user" USING btree (email);


--
-- Name: uniq_activity_user_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_activity_user_date ON public.daily_activity_log USING btree (user_id, logged_on);


--
-- Name: uniq_nutrition_user_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_nutrition_user_date ON public.nutrition_log USING btree (user_id, logged_on);


--
-- Name: uniq_weight_user_date; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX uniq_weight_user_date ON public.weight_log USING btree (user_id, logged_on);


--
-- Name: nutrition_log fk_18b697fa76ed395; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nutrition_log
    ADD CONSTRAINT fk_18b697fa76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: program_assignment fk_26ffb90e3eb8070a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.program_assignment
    ADD CONSTRAINT fk_26ffb90e3eb8070a FOREIGN KEY (program_id) REFERENCES public.program(id) ON DELETE CASCADE;


--
-- Name: program_assignment fk_26ffb90ea76ed395; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.program_assignment
    ADD CONSTRAINT fk_26ffb90ea76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: workout_template fk_4f11f2353eb8070a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_template
    ADD CONSTRAINT fk_4f11f2353eb8070a FOREIGN KEY (program_id) REFERENCES public.program(id) ON DELETE CASCADE;


--
-- Name: weight_log fk_6bbb9e9ca76ed395; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.weight_log
    ADD CONSTRAINT fk_6bbb9e9ca76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: workout_set fk_6fdefb94613fecdf; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_set
    ADD CONSTRAINT fk_6fdefb94613fecdf FOREIGN KEY (session_id) REFERENCES public.workout_session(id) ON DELETE CASCADE;


--
-- Name: workout_set fk_6fdefb94e934951a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_set
    ADD CONSTRAINT fk_6fdefb94e934951a FOREIGN KEY (exercise_id) REFERENCES public.exercise(id);


--
-- Name: daily_activity_log fk_70dabd61a76ed395; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.daily_activity_log
    ADD CONSTRAINT fk_70dabd61a76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: user fk_8d93d6493c105691; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT fk_8d93d6493c105691 FOREIGN KEY (coach_id) REFERENCES public."user"(id) ON DELETE SET NULL;


--
-- Name: exercise_template fk_910cbf6b8db41c9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_template
    ADD CONSTRAINT fk_910cbf6b8db41c9 FOREIGN KEY (workout_template_id) REFERENCES public.workout_template(id) ON DELETE CASCADE;


--
-- Name: exercise_template fk_910cbf6be934951a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise_template
    ADD CONSTRAINT fk_910cbf6be934951a FOREIGN KEY (exercise_id) REFERENCES public.exercise(id);


--
-- Name: program fk_92ed7784b03a8386; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT fk_92ed7784b03a8386 FOREIGN KEY (created_by_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: workout_session fk_ac82b97c39a55f18; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_session
    ADD CONSTRAINT fk_ac82b97c39a55f18 FOREIGN KEY (source_template_id) REFERENCES public.workout_template(id) ON DELETE SET NULL;


--
-- Name: workout_session fk_ac82b97ca76ed395; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workout_session
    ADD CONSTRAINT fk_ac82b97ca76ed395 FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: exercise fk_aedad51cb03a8386; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.exercise
    ADD CONSTRAINT fk_aedad51cb03a8386 FOREIGN KEY (created_by_id) REFERENCES public."user"(id) ON DELETE SET NULL;


--
-- Name: chat_message fk_chat_message_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT fk_chat_message_user FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict wg3umkTeDebgVaNcqERaF7tNcGYwoukFpPTxs21DDlUZgu37jl4ggdZxDRWbhOl

