<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522183225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chat_message ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chat_message ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN chat_message.created_at IS \'\'');
        $this->addSql('COMMENT ON COLUMN "user".google_access_expires_at IS \'\'');
        $this->addSql('ALTER TABLE weight_log ADD image_filename VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chat_message ALTER id SET DEFAULT nextval(\'chat_message_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chat_message ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN chat_message.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".google_access_expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE weight_log DROP image_filename');
    }
}
